set names 'utf8';
create database bulgaria character set utf8 collate utf8_general_ci;
grant all on bulgaria.* to 'web_user'@'%' identified by 'Parola1';
use bulgaria;
create table cities (id int primary key auto_increment, city_name varchar(50), population int);
INSERT INTO cities (city_name, population) VALUES ('Варна', 3236047);
INSERT INTO cities (city_name, population) VALUES ('София', 1343424);
INSERT INTO cities (city_name, population) VALUES ('Пловдив', 335177);
INSERT INTO cities (city_name, population) VALUES ('Бургас', 202766);
INSERT INTO cities (city_name, population) VALUES ('Хасково', 144936);
INSERT INTO cities (city_name, population) VALUES ('Стара Загора', 136781);
INSERT INTO cities (city_name, population) VALUES ('Плевен', 98467);
INSERT INTO cities (city_name, population) VALUES ('Сливен', 87322);
INSERT INTO cities (city_name, population) VALUES ('Добрич', 85402);
INSERT INTO cities (city_name, population) VALUES ('Шумен', 76967);
INSERT INTO cities (city_name, population) VALUES ('с.Кичево', 1208);
INSERT INTO cities (city_name, population) VALUES ('Дриги градове', 6311208);
